title: Front in Vale
year: 2015
email: contato@frontinvale.com.br
description: Primeiro evento de front-end no Vale do Paraíba.
keywords: 'frontend, front-end, html, html5, css, css3, javascript, js'
baseurl: ""
image_social: '/images/frontinvale-social.png'
url: "http://frontinvale.com.br"
twitter_username: frontinvale
github_username:  frontinvale

markdown: kramdown

collections:
- sponsors
- sponsors-ouro
- sponsors-prata
- sponsors-bronze
- speakers
- filmmakers
